sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: djx-beibei'blog
name: djx-beibei
description: Welcome to your friend , djx-beibei's blog . 

github: https://github.com/djx-beibei/djx-beibei.github.io
rss: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock

theme: jekyll-theme-minimal